export type TechnologyName =
  | "React"
  | "React Native"
  | "JavaScript"
  | "HTML"
  | "CSS"
  | "Tailwind"
  | "Bootstrap"
  | "Chakra"
  | "jQuery"
  | "GitHub"
  | "Node.js"
  | "Express.js"
  | "MongoDB"
  | "Handlebars"
  | "MySQL"
  | "Sequelize"
  | "Bulma"
  | "Heroku"
  | "Vercel"
  | "Framer Motion"
  | "Vite"
  | "Radix UI"
  | "Next.js"
  | "Clerk"
  | "Refresh"
  | "React Router"
  | "npm"
  | "Figma"
  | "Mongoose"
  | "Render"
  | "Expo"
  | "Google AdMob"
  | "App Store"
  | "Docusaurus"
  | "Markdown"
  | "TypeScript"
  | "AWS Lambda"
  | "AWS DynamoDB"
  | "AWS S3"
  | "OpenAPI"
  | "Vitest"
  | "Docker"
  | "Mantine UI"
  | "AWS";
